package com.itesm.ecommerce.application.service;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.UserRecord;
import com.google.firebase.auth.UserRecord.CreateRequest;
import com.itesm.ecommerce.domain.model.User;
import com.itesm.ecommerce.domain.repository.UserRepository;
import jakarta.inject.Inject;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.transaction.Transactional;

@ApplicationScoped
public class SignUpService {
    @Inject
    UserRepository userRepository;

    public User signUp(String email, String password) throws Exception {
        CreateRequest request = new CreateRequest()
            .setEmail(email)
            .setPassword(password)
            .setEmailVerified(false)
            .setDisabled(false);

        UserRecord userRecord = FirebaseAuth.getInstance().createUser(request);

        User user = new User();
        user.setFirebaseId(userRecord.getUid());
        // The ID will be auto-generated by the database
        return userRepository.createUser(user);
    }
}
